//! Isabelle/HOL backend for adsmt-cert certificates.
//!
//! Produces a `.thy` source file that re-states an adsmt
//! [`Certificate`] as a sequence of
//! `axiomatization` / `lemma ... by ...` declarations. Each cert
//! step becomes a named entity in the theory; the conclusion is
//! exposed as `theorem result: "<concl>" using s<final> by simp`.
//!
//! Lockstep with [`adsmt_cert::prover_emit::common`]. Lean is the
//! reference shape; this crate mirrors it with the per-prover
//! syntactic adjustments documented in the cross-ITP output policy.
//!
//! # Mapping highlights
//!
//! | cert StepBody | Isabelle/HOL emit |
//! |---|---|
//! | `Assume(φ)` | `axiomatization where s<i>: "φ"` |
//! | `Refl(t)` | `lemma s<i>: "t = t" by simp` |
//! | `Trans { lhs, rhs }` | `lemma s<i>: "<concl>" sorry  -- TODO: trans s<lhs> s<rhs>` |
//! | `EqMp { iff, p }` | `lemma s<i>: "<concl>" sorry  -- TODO: blast s<iff> s<p>` |
//! | `Deduct`/`Abs`/`Beta`/`Inst`/`InstType` | `lemma s<i>: "<concl>" sorry` |
//! | `Theory { name, witness, parents }` | `axiomatization where s<i>: "<concl>"  (* theory ... *)` |
//! | `Assumed { φ, explain }` | `lemma s<i>: "φ" sorry  (* abductive: ... *)` |
//! | Final | `theorem result: "<concl>" using s<final> by simp` |
//!
//! Free term variables emit as `consts <name> :: "bool"` — the
//! Isabelle/HOL `bool` sort is the proposition family in classical
//! HOL; semantically equivalent to Lean / Rocq `Prop`.

use std::fmt::Write;

use adsmt_cert::canonical::{Certificate, Step, StepBody};
use adsmt_cert::prover_emit::common::{escape_for_comment, witness_summary};
use adsmt_cert::TheoryWitness;
use adsmt_core::{Term, TermInner};

/// Emit a self-contained Isabelle theory source string for `cert`.
///
/// Per the "Classical axiom imports (on-demand)" policy, Isabelle's
/// `Main` already imports classical machinery — every family in
/// [`adsmt_cert::ClassicalModuleFamily`] maps to a no-op on the
/// Isabelle side. So no `imports` line is added beyond `Main`.
/// The validation pass still runs, however: a cert with uncovered
/// classical-axiom requirements still causes [`emit_isabelle`] to
/// panic (D1.E-3 = α no escape hatch). Use [`try_emit_isabelle`]
/// to inspect or recover.
///
/// The reason to keep the validation pass even though no import
/// line lands: symmetry with Lean and Rocq lets cert producers
/// catch missing markers before any of the three backends are
/// invoked. A cert that emits cleanly on Isabelle but panics on
/// Rocq would be a confusing partial-pass state; validating
/// uniformly catches it on every backend.
pub fn emit_isabelle(cert: &Certificate) -> String {
    match try_emit_isabelle(cert) {
        Ok(s) => s,
        Err(MissingImports(pairs)) => {
            let detail = pairs
                .iter()
                .map(|(sid, fam)| format!("s{}:{:?}", sid.0, fam))
                .collect::<Vec<_>>()
                .join(", ");
            panic!(
                "adsmt-emit-isabelle: cert has uncovered classical-axiom \
                 requirements: [{detail}]. \
                 Add `should_import_classical` or `allow_to_import_classical` \
                 markers on the offending steps. (Note: Isabelle/HOL's `Main` \
                 already imports classical machinery, so no actual `imports` \
                 line is emitted — but the marker check still gates emission \
                 for symmetry with Lean/Rocq.)"
            );
        }
    }
}

/// One uncovered `(step, family)` pair per offending position
/// (D1.E-2 = δ).
#[derive(Debug)]
pub struct MissingImports(
    pub Vec<(adsmt_cert::StepId, adsmt_cert::ClassicalModuleFamily)>,
);

/// Fallible variant of [`emit_isabelle`].
pub fn try_emit_isabelle(cert: &Certificate) -> Result<String, MissingImports> {
    use adsmt_cert::prover_emit::common::{
        aggregate_required, isabelle_axiom_keywords, missing_imports,
        resolve_imports_with_scan,
    };
    use adsmt_cert::ClassicalSet;

    // v0.19 A.5: two-pass scan=true wiring. Isabelle's keyword
    // table is empty (Main is classical), so the scan arm
    // produces no extra imports. The two-pass shape is preserved
    // for parity with Lean/Rocq — symmetric runtime cost matters
    // less than predictable behaviour across backends.
    let preliminary = render_body(cert);
    let resolved = resolve_imports_with_scan(
        cert,
        &ClassicalSet::empty(),
        &[],
        &preliminary,
        isabelle_axiom_keywords,
    );
    let required = aggregate_required(cert);
    if !required.is_empty() {
        let missing = missing_imports(cert, &resolved);
        if !missing.is_empty() {
            return Err(MissingImports(missing));
        }
    }

    let mut out = String::new();
    out.push_str("(* Generated by adsmt-emit-isabelle (HOL via Isar) *)\n");
    out.push_str("(* One `consts` per free term variable, one decl per cert step *)\n");
    out.push_str("theory AdsmtCert\n  imports Main\nbegin\n\n");

    let vars = collect_free_vars(cert);
    if !vars.is_empty() {
        for (name, ty) in &vars {
            writeln!(out, "consts {name} :: \"{ty}\"").unwrap();
        }
        out.push('\n');
    }

    for step in &cert.steps {
        emit_step(step, &mut out);
    }

    if let Some(seq) = cert.final_sequent() {
        let concl_isa = render_term(&seq.concl);
        let final_id = format!("s{}", cert.conclusion.0);
        writeln!(
            out,
            "\ntheorem result: \"{concl_isa}\" using {final_id} by simp"
        )
        .unwrap();
    }
    out.push_str("\nend\n");
    Ok(out)
}

/// Render the cert body for [`try_emit_isabelle`]'s pass-1
/// preliminary text. Identical shape to the final emit.
fn render_body(cert: &Certificate) -> String {
    let mut out = String::new();
    out.push_str("theory AdsmtCert\n  imports Main\nbegin\n\n");
    let vars = collect_free_vars(cert);
    if !vars.is_empty() {
        for (name, ty) in &vars {
            writeln!(out, "consts {name} :: \"{ty}\"").unwrap();
        }
        out.push('\n');
    }
    for step in &cert.steps {
        emit_step(step, &mut out);
    }
    if let Some(seq) = cert.final_sequent() {
        let concl_isa = render_term(&seq.concl);
        let final_id = format!("s{}", cert.conclusion.0);
        writeln!(
            out,
            "\ntheorem result: \"{concl_isa}\" using {final_id} by simp"
        )
        .unwrap();
    }
    out.push_str("\nend\n");
    out
}

fn emit_step(step: &Step, out: &mut String) {
    let name = format!("s{}", step.id.0);
    let concl_isa = render_term(&step.result.concl);

    match &step.body {
        StepBody::Assume(t) => {
            writeln!(
                out,
                "axiomatization where {name}: \"{}\"",
                render_term(t),
            )
            .unwrap();
        }
        StepBody::Refl(t) => {
            let t_isa = render_term(t);
            writeln!(out, "lemma {name}: \"{t_isa} = {t_isa}\" by simp").unwrap();
        }
        StepBody::Trans { lhs, rhs } => {
            writeln!(
                out,
                "lemma {name}: \"{concl_isa}\" sorry  (* TODO: trans s{} s{} *)",
                lhs.0, rhs.0,
            )
            .unwrap();
        }
        StepBody::EqMp { iff, p } => {
            writeln!(
                out,
                "lemma {name}: \"{concl_isa}\" sorry  (* TODO: blast s{} s{} *)",
                iff.0, p.0,
            )
            .unwrap();
        }
        StepBody::Deduct { a, b } => {
            // v0.19 K-full: real Isar proof via `using ... by blast`.
            // Isabelle's blast tactic handles propositional
            // deduction over the supplied hypotheses.
            writeln!(
                out,
                "lemma {name}: \"{concl_isa}\" using s{} s{} by blast",
                a.0, b.0,
            )
            .unwrap();
        }
        StepBody::Beta { redex } => {
            // v0.19 K-full: β-reduction yields a definitional
            // equality; Isabelle's `simp` discharges it.
            writeln!(
                out,
                "lemma {name}: \"{concl_isa}\" by simp  (* β-reduce: {} *)",
                escape_for_comment(&render_term(redex)),
            )
            .unwrap();
        }
        StepBody::Abs { var, eq } => {
            // v0.19 K-full: function-equality from pointwise
            // equality. Isabelle's `ext` rule + the pointwise
            // proof discharge it.
            writeln!(
                out,
                "lemma {name}: \"{concl_isa}\" using s{} by (rule ext)  (* abs over {} *)",
                eq.0, var.name,
            )
            .unwrap();
        }
        StepBody::Inst { thm, .. } => {
            // v0.19 K-full: Isabelle's `OF` / type unification
            // handles instantiation automatically when the goal
            // type is concrete enough.
            writeln!(
                out,
                "lemma {name}: \"{concl_isa}\" using s{} by simp",
                thm.0,
            )
            .unwrap();
        }
        StepBody::InstType { thm, .. } => {
            writeln!(
                out,
                "lemma {name}: \"{concl_isa}\" using s{} by simp",
                thm.0,
            )
            .unwrap();
        }
        StepBody::Theory {
            name: theory_name,
            witness,
            parents,
        } => {
            writeln!(
                out,
                "(* theory `{theory_name}` step; witness: {} *)",
                witness_summary_local(witness),
            )
            .unwrap();
            if !parents.is_empty() {
                write!(out, "(* parents:").unwrap();
                for p in parents {
                    write!(out, " s{}", p.0).unwrap();
                }
                out.push_str(" *)\n");
            }
            writeln!(
                out,
                "axiomatization where {name}: \"{concl_isa}\""
            )
            .unwrap();
        }
        StepBody::Instance { relation, .. } => {
            writeln!(out, "(* type-class instance for `{relation}` *)").unwrap();
            writeln!(
                out,
                "axiomatization where {name}: \"{concl_isa}\""
            )
            .unwrap();
        }
        StepBody::Assumed { formula, explain } => {
            let explain_str = explain.as_deref().unwrap_or("");
            writeln!(
                out,
                "(* abductive marker: {} *)",
                escape_for_comment(explain_str),
            )
            .unwrap();
            writeln!(
                out,
                "lemma {name}: \"{}\" sorry",
                render_term(formula),
            )
            .unwrap();
        }
    }
}

fn witness_summary_local(w: &TheoryWitness) -> String {
    witness_summary(w)
}

fn collect_free_vars(cert: &Certificate) -> Vec<(String, String)> {
    let mut seen: Vec<(String, String)> = Vec::new();
    for step in &cert.steps {
        for hyp in &step.result.hyps {
            for v in hyp.free_vars() {
                let entry = (v.name.clone(), render_type(&v.ty));
                if !seen.contains(&entry) {
                    seen.push(entry);
                }
            }
        }
        for v in step.result.concl.free_vars() {
            let entry = (v.name.clone(), render_type(&v.ty));
            if !seen.contains(&entry) {
                seen.push(entry);
            }
        }
    }
    seen
}

/// Render an adsmt [`Term`] as an Isabelle/HOL expression. Goes
/// inside a `"..."`-quoted source position, so any character that
/// would close the literal is intentionally avoided by the
/// mappings below.
fn render_term(t: &Term) -> String {
    if let Some((lhs, rhs)) = t.dest_eq() {
        return format!("({} = {})", render_term(&lhs), render_term(&rhs));
    }
    if let Some((head, args)) = adsmt_cert::prover_emit::common::strip_app_head(t) {
        match (head.as_str(), args.len()) {
            ("not", 1) => return format!("(\\<not> {})", render_term(&args[0])),
            ("and", 2) => {
                return format!(
                    "({} \\<and> {})",
                    render_term(&args[0]),
                    render_term(&args[1])
                )
            }
            ("or", 2) => {
                return format!(
                    "({} \\<or> {})",
                    render_term(&args[0]),
                    render_term(&args[1])
                )
            }
            ("implies", 2) | ("=>", 2) => {
                return format!(
                    "({} \\<longrightarrow> {})",
                    render_term(&args[0]),
                    render_term(&args[1])
                )
            }
            ("iff", 2) => {
                return format!(
                    "({} \\<longleftrightarrow> {})",
                    render_term(&args[0]),
                    render_term(&args[1])
                )
            }
            _ => {}
        }
    }
    // rc.10 (verus-fork R1) reshaped `Term` from an enum to
    // `Term(Arc<TermInner>)`; pattern-match through `kind()`
    // against `TermInner::*` (the bare `Term::App` etc. are now
    // associated constructor fns, not variants).
    match t.kind() {
        TermInner::Var(v) => v.name.clone(),
        TermInner::Const(c) => c.name.clone(),
        TermInner::App(f, x) => {
            let f_s = render_term(f);
            let x_s = render_term(x);
            let x_render = if matches!(x.kind(), TermInner::App(..) | TermInner::Lam(..)) {
                format!("({x_s})")
            } else {
                x_s
            };
            format!("{f_s} {x_render}")
        }
        TermInner::Lam(v, body) => format!(
            "(\\<lambda>{} :: {}. {})",
            v.name,
            render_type(&v.ty),
            render_term(body),
        ),
    }
}

/// Render an adsmt [`Type`] as Isabelle/HOL type syntax. adsmt
/// `Bool` becomes `bool` — the proposition family in HOL.
fn render_type(ty: &adsmt_core::Type) -> String {
    if let Some((dom, cod)) = ty.dest_fun() {
        return format!("({} \\<Rightarrow> {})", render_type(&dom), render_type(&cod));
    }
    match ty.to_string().as_str() {
        "Bool" => "bool".into(),
        "Int" => "int".into(),
        "Real" => "real".into(),
        other => other.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use adsmt_cert::recorder::{recorder as r, ProofHandle};
    use adsmt_core::{Term, Type};

    fn p() -> Term {
        Term::var("p", Type::bool_())
    }

    #[test]
    fn header_and_theory_present() {
        let mut b = adsmt_cert::canonical::CertBuilder::default();
        let h = r::assume(&mut b, p()).unwrap();
        let cert = b.snapshot(h.step());
        let s = emit_isabelle(&cert);
        assert!(s.starts_with("(* Generated by adsmt-emit-isabelle"));
        assert!(s.contains("theory AdsmtCert"));
        assert!(s.contains("imports Main"));
        assert!(s.contains("begin"));
        assert!(s.ends_with("end\n"));
    }

    #[test]
    fn assume_emits_axiomatization_with_term() {
        let mut b = adsmt_cert::canonical::CertBuilder::default();
        let h: ProofHandle = r::assume(&mut b, p()).unwrap();
        let cert = b.snapshot(h.step());
        let s = emit_isabelle(&cert);
        assert!(s.contains("consts p :: \"bool\""));
        assert!(s.contains(&format!("axiomatization where s{}: \"p\"", h.step().0)));
        assert!(s.contains("theorem result: \"p\" using s0 by simp"));
    }

    #[test]
    fn refl_emits_simp_lemma() {
        let mut b = adsmt_cert::canonical::CertBuilder::default();
        let h = r::refl(&mut b, &p()).unwrap();
        let cert = b.snapshot(h.step());
        let s = emit_isabelle(&cert);
        assert!(s.contains("lemma s0: \"p = p\" by simp"));
    }

    #[test]
    fn assumed_marker_emits_sorry_with_explain_comment() {
        let mut b = adsmt_cert::canonical::CertBuilder::default();
        let h =
            r::assumed(&mut b, p(), Some("needs Functor MyType".into())).unwrap();
        let cert = b.snapshot(h.step());
        let s = emit_isabelle(&cert);
        assert!(s.contains("(* abductive marker: needs Functor MyType *)"));
        assert!(s.contains("lemma s0: \"p\" sorry"));
    }

    #[test]
    fn negated_assumption_uses_isabelle_not_symbol() {
        let mut b = adsmt_cert::canonical::CertBuilder::default();
        let np = Term::mk_not(p()).unwrap();
        let h = r::assume(&mut b, np).unwrap();
        let cert = b.snapshot(h.step());
        let s = emit_isabelle(&cert);
        assert!(s.contains("axiomatization where s0: \"(\\<not> p)\""));
    }

    #[test]
    fn theory_step_axiomatizes_with_witness_comment() {
        use adsmt_cert::canonical::{Sequent, StepBody};
        let mut b = adsmt_cert::canonical::CertBuilder::default();
        let assume = r::assume(&mut b, p()).unwrap();
        let theory_step = b.add(
            StepBody::Theory {
                name: "EUF".into(),
                witness: TheoryWitness::Opaque {
                    kind: "smoke".into(),
                    notes: "demo".into(),
                },
                parents: vec![assume.step()],
            },
            Sequent {
                hyps: vec![p()],
                concl: p(),
            },
        );
        let cert = b.snapshot(theory_step);
        let s = emit_isabelle(&cert);
        assert!(s.contains("(* theory `EUF` step"));
        assert!(s.contains("Opaque(smoke)"));
        assert!(s.contains(&format!("axiomatization where s{}: \"p\"", theory_step.0)));
    }

    // === Classical-axiom-import validation ===

    #[test]
    fn no_extra_imports_for_intuitionistic_cert() {
        // Isabelle Main is classical — no extra imports land
        // regardless of markers. But the line `imports Main`
        // stays.
        let mut b = adsmt_cert::canonical::CertBuilder::default();
        let h = r::assume(&mut b, p()).unwrap();
        let cert = b.snapshot(h.step());
        let s = emit_isabelle(&cert);
        // imports header has Main only.
        assert!(s.contains("imports Main"));
        // No extra `imports` line beyond the fixed prelude.
        assert_eq!(s.matches("imports").count(), 1);
    }

    #[test]
    fn should_marker_propositional_still_emits_only_main() {
        use adsmt_cert::ClassicalModuleFamily;
        let mut b = adsmt_cert::canonical::CertBuilder::default();
        let h = r::assume(&mut b, p()).unwrap();
        let step_id = h.step();
        b.add_should_import_classical(
            step_id,
            ClassicalModuleFamily::Propositional,
        );
        let cert = b.snapshot(step_id);
        let s = emit_isabelle(&cert);
        // Marker is respected at the validation layer but
        // produces no Isabelle-side line (Main is classical).
        assert!(s.contains("imports Main"));
        assert_eq!(s.matches("imports").count(), 1);
    }

    #[test]
    fn try_emit_isabelle_returns_error_when_required_uncovered() {
        use adsmt_cert::{ClassicalModuleFamily, ClassicalSet};
        let mut b = adsmt_cert::canonical::CertBuilder::default();
        let h = r::assume(&mut b, p()).unwrap();
        let step_id = h.step();
        b.set_direct_required_classical(
            step_id,
            ClassicalSet::from_iter([ClassicalModuleFamily::Propositional]),
        );
        let cert = b.snapshot(step_id);
        let result = try_emit_isabelle(&cert);
        assert!(matches!(result, Err(MissingImports(_))));
    }

    #[test]
    fn mid_block_pattern_markers_passing_validation_for_isabelle() {
        // Isabelle's Main is classical so no extra import lands
        // regardless of the contributing layer. This test
        // confirms the contrib backend at least passes the
        // hard validation when mid-block + pattern markers
        // cover any (hypothetical) requirements via the shared
        // aggregator.
        use adsmt_cert::{
            ClassicalMarkerSet, ClassicalModuleFamily, ClassicalSet, MidBlock,
            MidBlockItem, PatternMarker, StepKindTag, StepPattern,
        };
        let mut b = adsmt_cert::canonical::CertBuilder::default();
        let h = r::assume(&mut b, p()).unwrap();
        let step_id = h.step();
        // Add a step-direct requirement that two layered markers
        // cover.
        b.set_direct_required_classical(
            step_id,
            ClassicalSet::from_iter([ClassicalModuleFamily::Propositional]),
        );
        // Mid-block exports the should.
        let block = MidBlock {
            name: Some("isa_block".into()),
            contents: vec![MidBlockItem::Step(step_id)],
            local_markers: ClassicalMarkerSet {
                should: ClassicalSet::from_iter([
                    ClassicalModuleFamily::Propositional,
                ]),
                allow: vec![],
            },
            exported_markers: ClassicalMarkerSet::empty(),
        };
        b.add_mid_block(block);
        // Pattern marker doubles up.
        b.add_pattern_marker(PatternMarker {
            pattern: StepPattern::Kind(StepKindTag::Assume),
            local_markers: ClassicalMarkerSet {
                should: ClassicalSet::from_iter([
                    ClassicalModuleFamily::Propositional,
                ]),
                allow: vec![],
            },
            name: Some("assume_marker".into()),
            source_loc: None,
        });
        let cert = b.snapshot(step_id);
        let result = try_emit_isabelle(&cert);
        assert!(result.is_ok());
        let s = result.unwrap();
        // Main only — no Classical_* line.
        assert!(s.contains("imports Main"));
        assert_eq!(s.matches("imports").count(), 1);
    }

    #[test]
    fn try_emit_isabelle_succeeds_when_marker_covers_requirement() {
        use adsmt_cert::{ClassicalModuleFamily, ClassicalSet};
        let mut b = adsmt_cert::canonical::CertBuilder::default();
        let h = r::assume(&mut b, p()).unwrap();
        let step_id = h.step();
        b.set_direct_required_classical(
            step_id,
            ClassicalSet::from_iter([ClassicalModuleFamily::Propositional]),
        );
        b.add_should_import_classical(
            step_id,
            ClassicalModuleFamily::Propositional,
        );
        let cert = b.snapshot(step_id);
        let result = try_emit_isabelle(&cert);
        assert!(result.is_ok());
        let s = result.unwrap();
        // Still only `imports Main` — Isabelle's classical
        // machinery comes from Main itself.
        assert!(s.contains("imports Main"));
    }
}
