//! Isabelle/HOL backend for adsmt-cert certificates.
//!
//! Produces a `.thy` source file that re-states an adsmt
//! [`Certificate`] as a sequence of
//! `axiomatization` / `lemma ... by ...` declarations. Each cert
//! step becomes a named entity in the theory; the conclusion is
//! exposed as `theorem result: "<concl>" using s<final> by simp`.
//!
//! Lockstep with [`adsmt_cert::prover_emit::common`]. Lean is the
//! reference shape; this crate mirrors it with the per-prover
//! syntactic adjustments documented in the cross-ITP output policy.
//!
//! # Mapping highlights
//!
//! | cert StepBody | Isabelle/HOL emit |
//! |---|---|
//! | `Assume(φ)` | `axiomatization where s<i>: "φ"` |
//! | `Refl(t)` | `lemma s<i>: "t = t" by simp` |
//! | `Trans { lhs, rhs }` | `lemma s<i>: "<concl>" sorry  -- TODO: trans s<lhs> s<rhs>` |
//! | `EqMp { iff, p }` | `lemma s<i>: "<concl>" sorry  -- TODO: blast s<iff> s<p>` |
//! | `Deduct`/`Abs`/`Beta`/`Inst`/`InstType` | `lemma s<i>: "<concl>" sorry` |
//! | `Theory { name, witness, parents }` | `axiomatization where s<i>: "<concl>"  (* theory ... *)` |
//! | `Assumed { φ, explain }` | `lemma s<i>: "φ" sorry  (* abductive: ... *)` |
//! | Final | `theorem result: "<concl>" using s<final> by simp` |
//!
//! Free term variables emit as `consts <name> :: "bool"` — the
//! Isabelle/HOL `bool` sort is the proposition family in classical
//! HOL; semantically equivalent to Lean / Rocq `Prop`.

use std::collections::BTreeSet;
use std::fmt::Write;

use adsmt_cert::canonical::{Certificate, Step, StepBody};
use adsmt_cert::prover_emit::common::{escape_for_comment, witness_summary};
use adsmt_cert::sexpr_render;
use adsmt_cert::TheoryWitness;
use adsmt_core::{Term, TermInner};

/// Emit a self-contained Isabelle theory source string for `cert`.
///
/// Per the "Classical axiom imports (on-demand)" policy, Isabelle's
/// `Main` already imports classical machinery — every family in
/// [`adsmt_cert::ClassicalModuleFamily`] maps to a no-op on the
/// Isabelle side. So no `imports` line is added beyond `Main`.
/// The validation pass still runs, however: a cert with uncovered
/// classical-axiom requirements still causes [`emit_isabelle`] to
/// panic (D1.E-3 = α no escape hatch). Use [`try_emit_isabelle`]
/// to inspect or recover.
///
/// The reason to keep the validation pass even though no import
/// line lands: symmetry with Lean and Rocq lets cert producers
/// catch missing markers before any of the three backends are
/// invoked. A cert that emits cleanly on Isabelle but panics on
/// Rocq would be a confusing partial-pass state; validating
/// uniformly catches it on every backend.
pub fn emit_isabelle(cert: &Certificate) -> String {
    match try_emit_isabelle(cert) {
        Ok(s) => s,
        Err(MissingImports(pairs)) => {
            let detail = pairs
                .iter()
                .map(|(sid, fam)| format!("s{}:{:?}", sid.0, fam))
                .collect::<Vec<_>>()
                .join(", ");
            panic!(
                "adsmt-emit-isabelle: cert has uncovered classical-axiom \
                 requirements: [{detail}]. \
                 Add `should_import_classical` or `allow_to_import_classical` \
                 markers on the offending steps. (Note: Isabelle/HOL's `Main` \
                 already imports classical machinery, so no actual `imports` \
                 line is emitted — but the marker check still gates emission \
                 for symmetry with Lean/Rocq.)"
            );
        }
    }
}

/// One uncovered `(step, family)` pair per offending position
/// (D1.E-2 = δ).
#[derive(Debug)]
pub struct MissingImports(
    pub Vec<(adsmt_cert::StepId, adsmt_cert::ClassicalModuleFamily)>,
);

/// Fallible variant of [`emit_isabelle`].
pub fn try_emit_isabelle(cert: &Certificate) -> Result<String, MissingImports> {
    use adsmt_cert::prover_emit::common::{
        aggregate_required, isabelle_axiom_keywords, missing_imports,
        resolve_imports_with_scan,
    };
    use adsmt_cert::ClassicalSet;

    // v0.19 A.5: two-pass scan=true wiring. Isabelle's keyword
    // table is empty (Main is classical), so the scan arm
    // produces no extra imports. The two-pass shape is preserved
    // for parity with Lean/Rocq — symmetric runtime cost matters
    // less than predictable behaviour across backends.
    let preliminary = render_body(cert);
    let resolved = resolve_imports_with_scan(
        cert,
        &ClassicalSet::empty(),
        &[],
        &preliminary,
        isabelle_axiom_keywords,
    );
    let required = aggregate_required(cert);
    if !required.is_empty() {
        let missing = missing_imports(cert, &resolved);
        if !missing.is_empty() {
            return Err(MissingImports(missing));
        }
    }

    let mut out = String::new();
    out.push_str("(* Generated by adsmt-emit-isabelle (HOL via Isar) *)\n");
    out.push_str("(* One `consts` per free term variable, one decl per cert step *)\n");
    // The target logic is not incidental: this is Isabelle/HOL, not Pure,
    // ZF, FOL or HOLCF. `Main`, `bool`, the `\<Longrightarrow>` /
    // `Trueprop` boundary and the tactics below are all HOL. Carrying the
    // session declaration inside the artifact pins that dependency in a
    // file instead of leaving it implicit, and it is what makes
    // `isabelle build` — the acceptance criterion — runnable at all.
    out.push_str("(* Target logic: Isabelle/HOL. Not valid over Pure, ZF, FOL or HOLCF. *)\n");
    out.push_str("(* Session declaration - write this next to the theory as `ROOT`:\n");
    for line in emit_isabelle_root().lines() {
        out.push_str("     ");
        out.push_str(line);
        out.push('\n');
    }
    out.push_str("*)\n");
    for sym in unmapped_constants(cert) {
        writeln!(
            out,
            "(* UNMAPPED SYMBOL: `{sym}` is emitted verbatim and may not \
parse in Isabelle/HOL. *)"
        )
        .unwrap();
    }
    for line in adsmt_cert::recheck::trust_summary(cert, "").lines() {
        writeln!(out, "(* {line} *)").unwrap();
    }
    out.push('\n');
    let mut imports = String::from("Main");
    for req in cert.signature.required_imports("isabelle") {
        imports.push(' ');
        imports.push_str(req);
    }
    writeln!(out, "theory AdsmtCert\n  imports {imports}\nbegin\n").unwrap();
    // A REGISTERED oracle, not `axiomatization`. The acceptance criterion
    // counts trust sources with `Thm_Deps.all_oracles`, and an
    // axiomatization does not appear there — only a registered oracle
    // does. This makes the single trust source both named and countable.
    out.push_str(
        "(* Trust source 1 of 2: the solver's own theory decisions. *)\n\
oracle adsmt = \\<open>fn ct => ct\\<close>\n\n",
    );
    // A SEPARATE oracle for user-supplied assumptions.
    //
    // Constraint (3)(C) rule 1: a user assumption must show up as a
    // second, distinct trust source. Routing it through the same
    // `adsmt` oracle would collapse both into one entry of
    // `Thm_Deps.all_oracles` — the reader would see "1 oracle" and have
    // no way to tell a theory decision from "assume this CryptHOL fact
    // holds". Invisible trust is not trust, it is an accident.
    if cert.steps.iter().any(|s| matches!(s.body, StepBody::Assumed { .. })) {
        out.push_str(
            "(* Trust source 2 of 2: USER-SUPPLIED assumptions. These are \
assumed,\n   not proved: everything below them is conditional on them. *)\n\
oracle adsmt_assumed = \\<open>fn ct => ct\\<close>\n\n",
        );
    }

    let declared = emit_declarations(cert, &mut out);
    let mut any_var = false;
    for (name, ty) in &collect_free_vars(cert) {
        if declared.contains(name) {
            continue;
        }
        writeln!(out, "consts {name} :: \"{ty}\"").unwrap();
        any_var = true;
    }
    if any_var {
        out.push('\n');
    }

    emit_oracles(cert, &mut out);

    if let Some(seq) = cert.final_sequent() {
        // Premise-preserving: hypotheses are discharged by the lemma
        // statement, never asserted as axioms.
        let hyps: Vec<String> = seq.hyps.iter().map(render_term).collect();
        let prop = isa_implication(&hyps, &render_term(&seq.concl));
        writeln!(out, "\nlemma result: \"{prop}\"").unwrap();
        out.push_str("proof -\n");
        for step in &cert.steps {
            emit_step(step, &mut out);
        }
        writeln!(out, "    show \"{}\" using s{} .", render_term(&seq.concl), cert.conclusion.0).unwrap();
        out.push_str("qed\n");
    }
    out.push_str("\nend\n");
    Ok(out)
}

/// Render the cert body for [`try_emit_isabelle`]'s pass-1
/// preliminary text. Identical shape to the final emit.
fn render_body(cert: &Certificate) -> String {
    let mut out = String::new();
    for sym in unmapped_constants(cert) {
        writeln!(
            out,
            "(* UNMAPPED SYMBOL: `{sym}` is emitted verbatim and may not \
parse in Isabelle/HOL. *)"
        )
        .unwrap();
    }
    for line in adsmt_cert::recheck::trust_summary(cert, "").lines() {
        writeln!(out, "(* {line} *)").unwrap();
    }
    out.push('\n');
    let mut imports = String::from("Main");
    for req in cert.signature.required_imports("isabelle") {
        imports.push(' ');
        imports.push_str(req);
    }
    writeln!(out, "theory AdsmtCert\n  imports {imports}\nbegin\n").unwrap();
    // A REGISTERED oracle, not `axiomatization`. The acceptance criterion
    // counts trust sources with `Thm_Deps.all_oracles`, and an
    // axiomatization does not appear there — only a registered oracle
    // does. This makes the single trust source both named and countable.
    out.push_str(
        "(* Trust source 1 of 2: the solver's own theory decisions. *)\n\
oracle adsmt = \\<open>fn ct => ct\\<close>\n\n",
    );
    // A SEPARATE oracle for user-supplied assumptions.
    //
    // Constraint (3)(C) rule 1: a user assumption must show up as a
    // second, distinct trust source. Routing it through the same
    // `adsmt` oracle would collapse both into one entry of
    // `Thm_Deps.all_oracles` — the reader would see "1 oracle" and have
    // no way to tell a theory decision from "assume this CryptHOL fact
    // holds". Invisible trust is not trust, it is an accident.
    if cert.steps.iter().any(|s| matches!(s.body, StepBody::Assumed { .. })) {
        out.push_str(
            "(* Trust source 2 of 2: USER-SUPPLIED assumptions. These are \
assumed,\n   not proved: everything below them is conditional on them. *)\n\
oracle adsmt_assumed = \\<open>fn ct => ct\\<close>\n\n",
        );
    }
    let declared = emit_declarations(cert, &mut out);
    let mut any_var = false;
    for (name, ty) in &collect_free_vars(cert) {
        if declared.contains(name) {
            continue;
        }
        writeln!(out, "consts {name} :: \"{ty}\"").unwrap();
        any_var = true;
    }
    if any_var {
        out.push('\n');
    }
    emit_oracles(cert, &mut out);
    if let Some(seq) = cert.final_sequent() {
        // Premise-preserving: hypotheses are discharged by the lemma
        // statement, never asserted as axioms.
        let hyps: Vec<String> = seq.hyps.iter().map(render_term).collect();
        let prop = isa_implication(&hyps, &render_term(&seq.concl));
        writeln!(out, "\nlemma result: \"{prop}\"").unwrap();
        out.push_str("proof -\n");
        for step in &cert.steps {
            emit_step(step, &mut out);
        }
        writeln!(out, "    show \"{}\" using s{} .", render_term(&seq.concl), cert.conclusion.0).unwrap();
        out.push_str("qed\n");
    }
    out.push_str("\nend\n");
    out
}

/// Conclusion of `id`, if that step exists.
fn step_concl(cert: &Certificate, id: adsmt_cert::StepId) -> Option<String> {
    cert.steps.iter().find(|s| s.id == id).map(|s| render_term(&s.result.concl))
}

/// `[p1; p2]`, `c` -> `p1 ==> p2 ==> c`; no premises -> just `c`.
fn isa_implication(prems: &[String], concl: &str) -> String {
    if prems.is_empty() {
        concl.to_owned()
    } else {
        format!("{} \\<Longrightarrow> {concl}", prems.join(" \\<Longrightarrow> "))
    }
}

/// Oracle axioms for steps no Isar tactic can replay.
///
/// Stated as *premises ==> conclusion*, never as the bare conclusion:
/// `axiomatization where s2: "False"` is false, whereas
/// `axiomatization where adsmt_s2: "p ==> ~p ==> False"` is true and
/// merely records the theory solver's decision, so the theory stays
/// consistent however contradictory the hypotheses are.

/// The oracle lemma's name for a step.
///
/// A USER-SUPPLIED assumption gets a visibly different name from a
/// theory decision, matching the separate `adsmt_assumed` oracle it is
/// discharged through (constraint (3)(C) rule 1).
fn oracle_name(step: &Step) -> String {
    match &step.body {
        StepBody::Assumed { .. } => format!("adsmt_assumed_s{}", step.id.0),
        _ => format!("adsmt_s{}", step.id.0),
    }
}

fn emit_oracles(cert: &Certificate, out: &mut String) {
    let mut any = false;
    for step in &cert.steps {
        let name = oracle_name(step);
        match &step.body {
            StepBody::Theory { name: theory_name, witness, parents } => {
                let prems: Vec<String> =
                    parents.iter().filter_map(|q| step_concl(cert, *q)).collect();
                let prop = isa_implication(&prems, &render_term(&step.result.concl));
                writeln!(out, "(* theory `{theory_name}`; witness: {} *)",
                         escape_for_comment(&witness_summary_local(witness))).unwrap();
                // Constraint (3)(B): a user tactic REPLACES the oracle.
                // Fail-first — Isabelle still checks the proof, so a
                // tactic that does not close the goal breaks the build
                // rather than being believed. On success the step stops
                // being a trust source at all.
                match cert.signature.tactic_for(step.id, Some(theory_name), "isabelle") {
                    Some(tac) => {
                        writeln!(out, "(* user tactic hint (replaces the oracle) *)").unwrap();
                        writeln!(out, "lemma {name}: \"{prop}\"\n  by {tac}").unwrap();
                    }
                    None => writeln!(out, "{}", isa_oracle_lemma(&name, &prop)).unwrap(),
                }
                any = true;
            }
            StepBody::Instance { relation, .. } => {
                writeln!(out, "(* type-class instance for `{relation}` *)").unwrap();
                writeln!(out, "{}",
                         isa_oracle_lemma(&name, &render_term(&step.result.concl))).unwrap();
                any = true;
            }
            StepBody::Assumed { formula, explain } => {
                writeln!(out, "(* USER-SUPPLIED ASSUMPTION (not proved): {} *)",
                         escape_for_comment(explain.as_deref().unwrap_or(""))).unwrap();
                writeln!(out, "{}",
                         isa_oracle_lemma_via("adsmt_assumed", &name,
                                              &render_term(formula))).unwrap();
                any = true;
            }
            _ => {}
        }
    }
    if any { out.push('\n'); }
}

/// Emit one step as an Isar fact inside the `result` proof.
///
/// `Assume` becomes an `assume`, not an axiom: it is discharged by the
/// enclosing `lemma "h1 ==> ... ==> hn ==> concl"`, so the theory never
/// asserts the hypotheses.
fn emit_step(step: &Step, out: &mut String) {
    let name = format!("s{}", step.id.0);
    let concl_isa = render_term(&step.result.concl);

    match &step.body {
        StepBody::Assume(t) => {
            writeln!(out, "    assume {name}: \"{}\"", render_term(t)).unwrap();
        }
        StepBody::Refl(t) => {
            let t_isa = render_term(t);
            writeln!(out, "    have {name}: \"{t_isa} = {t_isa}\" by simp").unwrap();
        }
        StepBody::Trans { lhs, rhs } => {
            writeln!(out, "    have {name}: \"{concl_isa}\" using s{} s{} by simp",
                     lhs.0, rhs.0).unwrap();
        }
        StepBody::MkComb { fun_eq, arg_eq } => {
            // HOL's `cong` is exactly this rule — `f = g ⟹ x = y ⟹ f x
            // = g y` — so the step is a REAL proof rather than an
            // oracle.
            writeln!(out, "    have {name}: \"{concl_isa}\" using s{} s{} by (rule cong)",
                     fun_eq.0, arg_eq.0).unwrap();
        }
        StepBody::EqMp { iff, p } => {
            writeln!(out, "    have {name}: \"{concl_isa}\" using s{} s{} by blast",
                     iff.0, p.0).unwrap();
        }
        StepBody::Deduct { a, b } => {
            writeln!(out, "    have {name}: \"{concl_isa}\" using s{} s{} by blast",
                     a.0, b.0).unwrap();
        }
        StepBody::Beta { redex } => {
            writeln!(out, "    have {name}: \"{concl_isa}\" by simp (* β-reduce: {} *)",
                     escape_for_comment(&render_term(redex))).unwrap();
        }
        StepBody::Abs { var, eq } => {
            writeln!(out, "    have {name}: \"{concl_isa}\" using s{} by (simp add: ext) (* abs {} *)",
                     eq.0, escape_for_comment(&var.name)).unwrap();
        }
        StepBody::Inst { thm, .. } | StepBody::InstType { thm, .. } => {
            writeln!(out, "    have {name}: \"{concl_isa}\" using s{} by blast", thm.0).unwrap();
        }
        StepBody::Theory { parents, .. } => {
            let args: Vec<String> = parents.iter().map(|q| format!("s{}", q.0)).collect();
            if args.is_empty() {
                writeln!(out, "    have {name}: \"{concl_isa}\" by (rule {})",
                         oracle_name(step)).unwrap();
            } else {
                writeln!(out, "    have {name}: \"{concl_isa}\" using adsmt_s{} {} by blast",
                         step.id.0, args.join(" ")).unwrap();
            }
        }
        StepBody::Instance { .. } | StepBody::Assumed { .. } => {
            writeln!(out, "    have {name}: \"{concl_isa}\" by (rule {})",
                     oracle_name(step)).unwrap();
        }
    }
}
fn witness_summary_local(w: &TheoryWitness) -> String {
    witness_summary(w)
}


/// Emit the certificate's declaration context — sorts, datatypes,
/// function signatures — and return every name it declared.
///
/// Constraint (1) rule 1. Without this the emitter reconstructed
/// declarations by scanning free variables, which cannot recover a sort
/// no term mentions, a constructor's arity, a selector name, or the
/// `declare-fun` vs `define-fun` distinction — the measured loss that
/// left `typedecl`/`datatype` missing from the output entirely.
fn emit_declarations(cert: &Certificate, out: &mut String) -> BTreeSet<String> {
    let sig = &cert.signature;
    // Constraint (3)(A): a user mapping says what a name MEANS in the
    // target — meaning the emitter cannot infer, and checkable, since
    // the emitted theory either typechecks or it does not.
    let render_sort_name = |s: &str| {
        let mapped = sig.mapped_name(s, "isabelle");
        if mapped == s { render_sort_name(s) } else { mapped.to_owned() }
    };
    let mut declared = BTreeSet::new();
    if sig.is_empty() {
        return declared;
    }

    // Uninterpreted sorts. HOL types are non-empty by construction, so
    // `typedecl` alone already says what SMT-LIB means — no companion
    // axiom is needed here (unlike Lean/Rocq).
    let user_sorts: Vec<_> = sig
        .sorts
        .iter()
        .filter(|s| {
            // A MAPPED sort already exists in the target, so
            // re-declaring it would shadow the real one.
            !s.builtin
                && !sig.datatypes.iter().any(|d| d.sort_name == s.name)
                && sig.mapped_name(&s.name, "isabelle") == s.name
        })
        .collect();
    if !user_sorts.is_empty() {
        out.push_str("(* Uninterpreted sorts *)\n");
        for s in &user_sorts {
            writeln!(out, "typedecl {}{}", type_params(s.arity as usize), s.name).unwrap();
            declared.insert(s.name.clone());
        }
        out.push('\n');
    }

    // Datatypes become real `datatype` declarations, so injectivity and
    // distinctness of constructors come from the package rather than
    // being asserted — and Isabelle's own selector syntax gives the
    // accessors for free.
    for d in &sig.datatypes {
        let params: String = if d.params.is_empty() {
            String::new()
        } else {
            let ps: Vec<String> = d.params.iter().map(|p| format!("'{p}")).collect();
            if ps.len() == 1 { format!("{} ", ps[0]) } else { format!("({}) ", ps.join(", ")) }
        };
        let mut alts: Vec<String> = Vec::new();
        for (i, ctor) in d.constructors.iter().enumerate() {
            let arity = d.arities.get(i).copied().unwrap_or(0) as usize;
            let fields = d.field_sorts.get(i);
            let sels = d.selectors.get(i);
            match fields {
                Some(fs) if fs.len() == arity => {
                    let mut alt = ctor.clone();
                    for (j, f) in fs.iter().enumerate() {
                        let ty = render_sort_name(f);
                        match sels.and_then(|s| s.get(j)) {
                            Some(sel) => {
                                write!(alt, " ({sel}: \"{ty}\")").unwrap();
                                declared.insert(sel.clone());
                            }
                            None => write!(alt, " \"{ty}\"").unwrap(),
                        }
                    }
                    alts.push(alt);
                }
                _ if arity == 0 => alts.push(ctor.clone()),
                // Arity without field sorts: we know the constructor
                // takes arguments but not of what type. Guessing would be
                // the silent mistranslation rule (1)(2) forbids.
                _ => {
                    writeln!(
                        out,
                        "(* INCOMPLETE: `{ctor}` takes {arity} argument(s) whose sorts \
the certificate did not carry *)"
                    )
                    .unwrap();
                    alts.push(ctor.clone());
                }
            }
            declared.insert(ctor.clone());
        }
        writeln!(out, "datatype {params}{} = {}", d.sort_name, alts.join(" | ")).unwrap();
        declared.insert(d.sort_name.clone());
        out.push('\n');
    }

    // Functions and constants. A `define-fun` keeps its definition — a
    // `definition`, not a `consts` — so the defining equation reaches
    // `simp` instead of being dropped.
    if !sig.funs.is_empty() {
        for f in &sig.funs {
            if sig.mapped_name(&f.name, "isabelle") != f.name {
                // Mapped to something the target already provides.
                declared.insert(f.name.clone());
                continue;
            }
            let ty = fun_type_in(sig, &f.params, &f.result);
            match &f.body {
                Some(body) => {
                    let mut unmapped = BTreeSet::new();
                    match sexpr_render::parse(body) {
                        Some(sx) => {
                            let rendered = sexpr_render::render(
                                &sx,
                                &sexpr_render::ISABELLE,
                                &mut unmapped,
                            );
                            for u in &unmapped {
                                writeln!(out, "(* UNMAPPED OPERATOR in `{}`: `{u}` *)", f.name)
                                    .unwrap();
                            }
                            let lhs_args: String =
                                f.param_names.iter().map(|n| format!(" {n}")).collect();
                            writeln!(out, "definition {} :: \"{ty}\" where", f.name).unwrap();
                            writeln!(out, "  \"{}{lhs_args} = {rendered}\"", f.name).unwrap();
                        }
                        None => {
                            writeln!(
                                out,
                                "(* UNPARSEABLE define-fun body for `{}`; emitted as \
uninterpreted *)",
                                f.name
                            )
                            .unwrap();
                            writeln!(out, "consts {} :: \"{ty}\"", f.name).unwrap();
                        }
                    }
                }
                None => writeln!(out, "consts {} :: \"{ty}\"", f.name).unwrap(),
            }
            declared.insert(f.name.clone());
        }
        out.push('\n');
    }
    declared
}

/// `('a, 'b) ` for arity 2; empty for arity 0.
fn type_params(arity: usize) -> String {
    if arity == 0 {
        return String::new();
    }
    let ps: Vec<String> = (0..arity).map(|i| format!("'{}", (b'a' + i as u8) as char)).collect();
    if ps.len() == 1 { format!("{} ", ps[0]) } else { format!("({}) ", ps.join(", ")) }
}

/// `["Int", "Int"]`, `"Bool"` -> `int \<Rightarrow> int \<Rightarrow> bool`.
fn fun_type_in(
    sig: &adsmt_cert::canonical::Signature,
    params: &[String],
    result: &str,
) -> String {
    let m = |s: &str| {
        let mapped = sig.mapped_name(s, "isabelle");
        if mapped == s { render_sort_name(s) } else { mapped.to_owned() }
    };
    let mut ty = String::new();
    for p in params {
        write!(ty, "{} \\<Rightarrow> ", m(p)).unwrap();
    }
    ty.push_str(&m(result));
    ty
}

/// A sort NAME as written in the declaration context, mapped the same
/// way [`render_type`] maps a `Type`.
fn render_sort_name(s: &str) -> String {
    match s {
        "Bool" => "bool".to_owned(),
        "Int" => "int".to_owned(),
        "Real" => "real".to_owned(),
        other => other.to_owned(),
    }
}

fn collect_free_vars(cert: &Certificate) -> Vec<(String, String)> {
    let mut seen: Vec<(String, String)> = Vec::new();
    for step in &cert.steps {
        for hyp in &step.result.hyps {
            for v in hyp.free_vars() {
                let entry = (v.name.clone(), render_type(&v.ty));
                if !seen.contains(&entry) {
                    seen.push(entry);
                }
            }
        }
        for v in step.result.concl.free_vars() {
            let entry = (v.name.clone(), render_type(&v.ty));
            if !seen.contains(&entry) {
                seen.push(entry);
            }
        }
    }
    seen
}

/// Render an adsmt [`Term`] as an Isabelle/HOL expression. Goes
/// inside a `"..."`-quoted source position, so any character that
/// would close the literal is intentionally avoided by the
/// mappings below.
fn render_term(t: &Term) -> String {
    if let Some((lhs, rhs)) = t.dest_eq() {
        return format!("({} = {})", render_term(&lhs), render_term(&rhs));
    }
    if let Some((head, args)) = adsmt_cert::prover_emit::common::strip_app_head(t) {
        match (head.as_str(), args.len()) {
            ("<", 2) => {
                return format!("({} < {})", render_term(&args[0]), render_term(&args[1]))
            }
            ("<=", 2) => {
                return format!("({} \\<le> {})", render_term(&args[0]), render_term(&args[1]))
            }
            (">", 2) => {
                return format!("({} > {})", render_term(&args[0]), render_term(&args[1]))
            }
            (">=", 2) => {
                return format!("({} \\<ge> {})", render_term(&args[0]), render_term(&args[1]))
            }
            ("+", 2) => {
                return format!("({} + {})", render_term(&args[0]), render_term(&args[1]))
            }
            ("-", 2) => {
                return format!("({} - {})", render_term(&args[0]), render_term(&args[1]))
            }
            ("*", 2) => {
                return format!("({} * {})", render_term(&args[0]), render_term(&args[1]))
            }
            ("not", 1) => return format!("(\\<not> {})", render_term(&args[0])),
            ("and", 2) => {
                return format!(
                    "({} \\<and> {})",
                    render_term(&args[0]),
                    render_term(&args[1])
                )
            }
            ("or", 2) => {
                return format!(
                    "({} \\<or> {})",
                    render_term(&args[0]),
                    render_term(&args[1])
                )
            }
            ("implies", 2) | ("=>", 2) => {
                return format!(
                    "({} \\<longrightarrow> {})",
                    render_term(&args[0]),
                    render_term(&args[1])
                )
            }
            ("iff", 2) => {
                return format!(
                    "({} \\<longleftrightarrow> {})",
                    render_term(&args[0]),
                    render_term(&args[1])
                )
            }
            _ => {}
        }
    }
    // rc.10 (verus-fork R1) reshaped `Term` from an enum to
    // `Term(Arc<TermInner>)`; pattern-match through `kind()`
    // against `TermInner::*` (the bare `Term::App` etc. are now
    // associated constructor fns, not variants).
    match t.kind() {
        TermInner::Var(v) => v.name.clone(),
        TermInner::Const(c) => match c.name.as_str() {
            // adsmt-core names the boolean constants `true` / `false`
            // (adsmt-core/src/term.rs:461,466). Those are *values of a
            // boolean type* in every target here, not propositions, so
            // emitting them verbatim produces source that does not compile.
            "true" => "True".to_owned(),
            "false" => "False".to_owned(),
            other => other.to_owned(),
        },
        TermInner::App(f, x) => {
            let f_s = render_term(f);
            let x_s = render_term(x);
            let x_render = if matches!(x.kind(), TermInner::App(..) | TermInner::Lam(..)) {
                format!("({x_s})")
            } else {
                x_s
            };
            format!("{f_s} {x_render}")
        }
        TermInner::Lam(v, body) => format!(
            "(\\<lambda>{} :: {}. {})",
            v.name,
            render_type(&v.ty),
            render_term(body),
        ),
    }
}

/// Render an adsmt [`Type`] as Isabelle/HOL type syntax. adsmt
/// `Bool` becomes `bool` — the proposition family in HOL.
fn render_type(ty: &adsmt_core::Type) -> String {
    use adsmt_core::Type as T;
    if let Some((dom, cod)) = ty.dest_fun() {
        return format!("({} \\<Rightarrow> {})", render_type(&dom), render_type(&cod));
    }
    // Isabelle's type application is POSTFIX — `int Seq`, not `Seq int`
    // — and multi-argument application is tupled: `('a, 'b) Map`.
    // Rendering the source's prefix form verbatim produces a type that
    // either fails to parse or, worse, parses as something else.
    if let T::App(..) = ty {
        let (head, args) = {
            let (mut cur, mut args) = (ty, Vec::new());
            while let T::App(f, a) = cur {
                args.push(render_type(a));
                cur = f;
            }
            args.reverse();
            (render_type(cur), args)
        };
        return match args.len() {
            1 => format!("{} {head}", args[0]),
            _ => format!("({}) {head}", args.join(", ")),
        };
    }
    match ty.to_string().as_str() {
        "Bool" => "bool".into(),
        "Int" => "int".into(),
        "Real" => "real".into(),
        other => other.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use adsmt_cert::recorder::{recorder as r, ProofHandle};
    use adsmt_core::{Term, Type};

    fn p() -> Term {
        Term::var("p", Type::bool_())
    }


    /// A certificate whose declaration context exercises every shape:
    /// an uninterpreted sort, a datatype with a nullary and an
    /// argument-bearing constructor plus selectors, an uninterpreted
    /// function, and a defined function.
    fn cert_with_declarations() -> Certificate {
        use adsmt_cert::canonical::{DatatypeDecl, FunDecl};
        let mut b = adsmt_cert::canonical::CertBuilder::default();
        b.declare_sort("Color", 0);
        b.declare_datatype(DatatypeDecl {
            sort_name: "Lst".into(),
            constructors: vec!["nil".into(), "cons".into()],
            arities: vec![0, 2],
            selectors: vec![vec![], vec!["hd".into(), "tl".into()]],
            field_sorts: vec![vec![], vec!["Int".into(), "Lst".into()]],
            params: vec![],
            is_finite: false,
        });
        b.declare_fun("f", vec!["Int".into()], "Bool", None);
        b.signature_mut().funs.push(FunDecl {
            name: "g".into(),
            params: vec!["Int".into()],
            param_names: vec!["x".into()],
            result: "Int".into(),
            body: Some("(+ x 1)".into()),
        });
        let h: ProofHandle = r::assume(&mut b, p()).unwrap();
        b.snapshot(h.step())
    }

    /// Acceptance criterion, constraint (1) rule 3: every sort and every
    /// datatype of the input must appear in the output AS A DECLARATION.
    ///
    /// The measured loss this closes: `typedecl`/`datatype` were absent
    /// from the output entirely, because declarations were reconstructed
    /// by scanning free variables — and a sort no term mentions is
    /// invisible to that scan.

    /// Isabelle's type application is POSTFIX. Rendering the source's
    /// prefix form verbatim produces a type that either fails to parse or
    /// parses as something else. Measured against Isabelle2026-RC0:
    /// `consts xs :: "int Seq"` builds; `"Seq int"` does not mean that.
    #[test]
    fn a_higher_kinded_type_is_rendered_structurally() {
        use adsmt_core::Kind;
        let seq = Type::const_("Seq", Kind::arrow(Kind::Type, Kind::Type));
        let applied = Type::app(seq, Type::bool_()).unwrap();
        assert_eq!(render_type(&applied), "bool Seq");
    }

    #[test]
    fn every_declared_sort_and_datatype_reaches_the_output() {
        let cert = cert_with_declarations();
        let s = emit_isabelle(&cert);
        for sort in cert.signature.sorts.iter().filter(|s| !s.builtin) {
            let declared = s.contains(&format!("typedecl {}", sort.name))
                || s.contains(&format!("datatype {}", sort.name));
            assert!(declared, "sort `{}` missing from output:\n{s}", sort.name);
        }
        for d in &cert.signature.datatypes {
            assert!(s.contains(&format!("datatype {}", d.sort_name)), "{s}");
            for c in &d.constructors {
                assert!(s.contains(c.as_str()), "ctor `{c}` missing:\n{s}");
            }
        }
    }

    #[test]
    fn declarations_carry_arity_selectors_and_definitions() {
        let s = emit_isabelle(&cert_with_declarations());
        // Isabelle's datatype package gives selectors from the
        // declaration itself, so the field sorts and accessor names both
        // ride along in one line.
        assert!(s.contains(r#"datatype Lst = nil | cons (hd: "int") (tl: "Lst")"#), "{s}");
        // `declare-fun` vs `define-fun`: uninterpreted vs defined.
        assert!(s.contains(r#"consts f :: "int \<Rightarrow> bool""#), "{s}");
        assert!(s.contains(r#"definition g :: "int \<Rightarrow> int" where"#), "{s}");
        assert!(s.contains(r#""g x = (x + 1)""#), "{s}");
        // A sort the datatype declares must not ALSO get a `typedecl`.
        assert!(!s.contains("typedecl Lst"), "{s}");
    }

    #[test]
    fn registered_oracle_is_the_only_trust_source() {
        // `axiomatization` states the fact but registers no trust source:
        // Thm_Deps.all_oracles reports nothing for it. Going through a
        // registered oracle makes the trust countable, which is exactly
        // what the acceptance criterion checks.
        use adsmt_cert::canonical::{Sequent, StepBody};
        let mut b = adsmt_cert::canonical::CertBuilder::default();
        let assume = r::assume(&mut b, p()).unwrap();
        let th = b.add(
            StepBody::Theory {
                name: "SAT".into(),
                witness: TheoryWitness::Opaque { kind: "k".into(), notes: "n".into() },
                parents: vec![assume.step()],
            },
            Sequent { hyps: vec![p()], concl: p() },
        );
        let s = emit_isabelle(&b.snapshot(th));
        assert!(s.contains("oracle adsmt ="), "no registered oracle:\n{s}");
        assert!(!s.contains("axiomatization"), "axiomatization remains:\n{s}");
        assert!(!s.contains("sorry"), "{s}");
        assert!(s.contains("by (tactic"), "oracle not applied via tactic:\n{s}");
    }

    #[test]
    fn session_declaration_travels_with_the_theory() {
        // Constraint (2): the emitted theory is HOL-specific, and the
        // acceptance criterion is stated as `isabelle build`, which needs a
        // session. Both the ROOT text and the target-logic note ship in the
        // artifact.
        let root = emit_isabelle_root();
        assert!(root.contains("session AdsmtCert = HOL +"), "{root}");
        assert!(root.contains("theories"), "{root}");

        let mut b = adsmt_cert::canonical::CertBuilder::default();
        let h = r::assume(&mut b, p()).unwrap();
        let s = emit_isabelle(&b.snapshot(h.step()));
        assert!(s.contains("session AdsmtCert = HOL +"), "{s}");
        assert!(s.contains("Target logic: Isabelle/HOL"), "{s}");
    }

    #[test]
    fn header_and_theory_present() {
        let mut b = adsmt_cert::canonical::CertBuilder::default();
        let h = r::assume(&mut b, p()).unwrap();
        let cert = b.snapshot(h.step());
        let s = emit_isabelle(&cert);
        assert!(s.starts_with("(* Generated by adsmt-emit-isabelle"));
        assert!(s.contains("theory AdsmtCert"));
        assert!(s.contains("imports Main"));
        assert!(s.contains("begin"));
        assert!(s.ends_with("end\n"));
    }

    #[test]
    fn assume_is_recorded_not_axiomatized() {
        // A hypothesis must NOT become an axiom. When every Assume was
        // axiomatized, a refutation certificate — whose hypotheses are
        // jointly unsatisfiable by construction — made the theory
        // inconsistent, and `theorem result` then held vacuously.
        let mut b = adsmt_cert::canonical::CertBuilder::default();
        let h: ProofHandle = r::assume(&mut b, p()).unwrap();
        let cert = b.snapshot(h.step());
        let s = emit_isabelle(&cert);
        assert!(s.contains("consts p :: \"bool\""));
        assert!(
            !s.contains(&format!("axiomatization where s{}:", h.step().0)),
            "hypothesis was axiomatized:\n{s}"
        );
        // It is an Isar `assume`, discharged by the lemma statement.
        assert!(s.contains("assume s0: \"p\""), "{s}");
        assert!(s.contains("lemma result:"), "{s}");
    }

    #[test]
    fn hypotheses_never_become_axioms() {
        // The verus-fork P0, as a regression test: assume p and assume ~p,
        // then check the emitted theory does not assert either one.
        let mut b = adsmt_cert::canonical::CertBuilder::default();
        let h1 = r::assume(&mut b, p()).unwrap();
        let np = Term::mk_not(p()).unwrap();
        let _h2 = r::assume(&mut b, np).unwrap();
        let cert = b.snapshot(h1.step());
        let s = emit_isabelle(&cert);
        for line in s.lines() {
            let l = line.trim();
            if l.starts_with("axiomatization where") {
                assert!(
                    l.contains("adsmt_result:"),
                    "an axiom other than the single trust source:\n{l}"
                );
            }
        }
    }

    #[test]
    fn output_carries_no_sorry() {
        let mut b = adsmt_cert::canonical::CertBuilder::default();
        let h = r::assumed(&mut b, p(), Some("abductive".into())).unwrap();
        let cert = b.snapshot(h.step());
        let s = emit_isabelle(&cert);
        assert!(!s.contains("sorry"), "sorry hides the gap from thm_oracles:\n{s}");
    }

    #[test]
    fn refl_is_proved_not_axiomatized() {
        let mut b = adsmt_cert::canonical::CertBuilder::default();
        let h = r::refl(&mut b, &p()).unwrap();
        let cert = b.snapshot(h.step());
        let s = emit_isabelle(&cert);
        // Replayable: a real Isar step, not an axiom and not a comment.
        assert!(s.contains("have s0: \"p = p\" by simp"), "{s}");
        assert!(!s.contains("axiomatization where s0:"), "{s}");
    }

    #[test]
    fn assumed_marker_becomes_a_named_oracle() {
        let mut b = adsmt_cert::canonical::CertBuilder::default();
        let h =
            r::assumed(&mut b, p(), Some("needs Functor MyType".into())).unwrap();
        let cert = b.snapshot(h.step());
        let s = emit_isabelle(&cert);
        // The abductive marker becomes a NAMED oracle axiom, so it shows
        // up as a trust source instead of hiding behind `sorry`.
        assert!(
            s.contains("(* USER-SUPPLIED ASSUMPTION (not proved): needs Functor MyType *)"),
            "{s}"
        );
        // A lemma discharged by a SEPARATE registered oracle, so
        // `Thm_Deps.all_oracles` reports it as a SECOND trust source
        // rather than folding it into the solver's own. Measured against
        // Isabelle2026-RC0: ORACLE_COUNT=2, NAMES=AdsmtCert.adsmt,
        // AdsmtCert.adsmt_assumed.
        assert!(s.contains("oracle adsmt_assumed ="), "{s}");
        assert!(s.contains("lemma adsmt_assumed_s0:"), "{s}");
        // `\<^cprop>`, not `\<^cterm>`: a bare `bool` proposition is
        // rejected with "Oracle's result must have type prop".
        assert!(s.contains("\\<^cprop>"), "{s}");
        assert!(s.contains("1 USER-SUPPLIED assumption(s)"), "{s}");
        assert!(s.contains("by (tactic"), "{s}");
        assert!(!s.contains("sorry"), "{s}");
        assert!(!s.contains("axiomatization"), "{s}");
    }

    #[test]
    fn negated_assumption_uses_isabelle_not_symbol() {
        // The negation still has to render with Isabelle's symbol — now it
        // shows up in the recorded step and in the single trust axiom
        // rather than in a per-step axiom.
        let mut b = adsmt_cert::canonical::CertBuilder::default();
        let np = Term::mk_not(p()).unwrap();
        let h = r::assume(&mut b, np).unwrap();
        let cert = b.snapshot(h.step());
        let s = emit_isabelle(&cert);
        assert!(s.contains("\\<not> p"), "{s}");
        assert!(!s.contains("axiomatization where s0:"), "{s}");
    }

    #[test]
    fn theory_step_records_its_witness_without_asserting() {
        use adsmt_cert::canonical::{Sequent, StepBody};
        let mut b = adsmt_cert::canonical::CertBuilder::default();
        let assume = r::assume(&mut b, p()).unwrap();
        let theory_step = b.add(
            StepBody::Theory {
                name: "EUF".into(),
                witness: TheoryWitness::Opaque {
                    kind: "smoke".into(),
                    notes: "demo".into(),
                },
                parents: vec![assume.step()],
            },
            Sequent {
                hyps: vec![p()],
                concl: p(),
            },
        );
        let cert = b.snapshot(theory_step);
        let s = emit_isabelle(&cert);
        // The witness survives as commentary, and the oracle axiom is
        // stated as PREMISES ==> CONCLUSION — that shape is what keeps the
        // theory consistent, since the bare conclusion could be `False`.
        assert!(s.contains("witness: Opaque(smoke)"), "{s}");
        assert!(
            !s.contains(&format!("axiomatization where s{}:", theory_step.0)),
            "{s}"
        );
        assert!(
            s.contains(&format!("lemma adsmt_s{}:", theory_step.0)),
            "{s}"
        );
        assert!(!s.contains("axiomatization"), "{s}");
        assert!(s.contains("\\<Longrightarrow>"), "oracle is not an implication:\n{s}");
    }

    // === Classical-axiom-import validation ===

    #[test]
    fn no_extra_imports_for_intuitionistic_cert() {
        // Isabelle Main is classical — no extra imports land
        // regardless of markers. But the line `imports Main`
        // stays.
        let mut b = adsmt_cert::canonical::CertBuilder::default();
        let h = r::assume(&mut b, p()).unwrap();
        let cert = b.snapshot(h.step());
        let s = emit_isabelle(&cert);
        // imports header has Main only.
        assert!(s.contains("imports Main"));
        // No extra `imports` line beyond the fixed prelude.
        assert_eq!(s.matches("imports").count(), 1);
    }

    #[test]
    fn should_marker_propositional_still_emits_only_main() {
        use adsmt_cert::ClassicalModuleFamily;
        let mut b = adsmt_cert::canonical::CertBuilder::default();
        let h = r::assume(&mut b, p()).unwrap();
        let step_id = h.step();
        b.add_should_import_classical(
            step_id,
            ClassicalModuleFamily::Propositional,
        );
        let cert = b.snapshot(step_id);
        let s = emit_isabelle(&cert);
        // Marker is respected at the validation layer but
        // produces no Isabelle-side line (Main is classical).
        assert!(s.contains("imports Main"));
        assert_eq!(s.matches("imports").count(), 1);
    }

    #[test]
    fn try_emit_isabelle_returns_error_when_required_uncovered() {
        use adsmt_cert::{ClassicalModuleFamily, ClassicalSet};
        let mut b = adsmt_cert::canonical::CertBuilder::default();
        let h = r::assume(&mut b, p()).unwrap();
        let step_id = h.step();
        b.set_direct_required_classical(
            step_id,
            ClassicalSet::from_iter([ClassicalModuleFamily::Propositional]),
        );
        let cert = b.snapshot(step_id);
        let result = try_emit_isabelle(&cert);
        assert!(matches!(result, Err(MissingImports(_))));
    }

    #[test]
    fn mid_block_pattern_markers_passing_validation_for_isabelle() {
        // Isabelle's Main is classical so no extra import lands
        // regardless of the contributing layer. This test
        // confirms the contrib backend at least passes the
        // hard validation when mid-block + pattern markers
        // cover any (hypothetical) requirements via the shared
        // aggregator.
        use adsmt_cert::{
            ClassicalMarkerSet, ClassicalModuleFamily, ClassicalSet, MidBlock,
            MidBlockItem, PatternMarker, StepKindTag, StepPattern,
        };
        let mut b = adsmt_cert::canonical::CertBuilder::default();
        let h = r::assume(&mut b, p()).unwrap();
        let step_id = h.step();
        // Add a step-direct requirement that two layered markers
        // cover.
        b.set_direct_required_classical(
            step_id,
            ClassicalSet::from_iter([ClassicalModuleFamily::Propositional]),
        );
        // Mid-block exports the should.
        let block = MidBlock {
            name: Some("isa_block".into()),
            contents: vec![MidBlockItem::Step(step_id)],
            local_markers: ClassicalMarkerSet {
                should: ClassicalSet::from_iter([
                    ClassicalModuleFamily::Propositional,
                ]),
                allow: vec![],
            },
            exported_markers: ClassicalMarkerSet::empty(),
        };
        b.add_mid_block(block);
        // Pattern marker doubles up.
        b.add_pattern_marker(PatternMarker {
            pattern: StepPattern::Kind(StepKindTag::Assume),
            local_markers: ClassicalMarkerSet {
                should: ClassicalSet::from_iter([
                    ClassicalModuleFamily::Propositional,
                ]),
                allow: vec![],
            },
            name: Some("assume_marker".into()),
            source_loc: None,
        });
        let cert = b.snapshot(step_id);
        let result = try_emit_isabelle(&cert);
        assert!(result.is_ok());
        let s = result.unwrap();
        // Main only — no Classical_* line.
        assert!(s.contains("imports Main"));
        assert_eq!(s.matches("imports").count(), 1);
    }

    #[test]
    fn try_emit_isabelle_succeeds_when_marker_covers_requirement() {
        use adsmt_cert::{ClassicalModuleFamily, ClassicalSet};
        let mut b = adsmt_cert::canonical::CertBuilder::default();
        let h = r::assume(&mut b, p()).unwrap();
        let step_id = h.step();
        b.set_direct_required_classical(
            step_id,
            ClassicalSet::from_iter([ClassicalModuleFamily::Propositional]),
        );
        b.add_should_import_classical(
            step_id,
            ClassicalModuleFamily::Propositional,
        );
        let cert = b.snapshot(step_id);
        let result = try_emit_isabelle(&cert);
        assert!(result.is_ok());
        let s = result.unwrap();
        // Still only `imports Main` — Isabelle's classical
        // machinery comes from Main itself.
        assert!(s.contains("imports Main"));
    }
}

/// A lemma discharged by the registered `adsmt` oracle.
///
/// `axiomatization` would also make the statement available, but it does
/// not register a trust source: `Thm_Deps.all_oracles` reports nothing for
/// it. Going through the oracle makes the trust both named and countable,
/// which is what the acceptance criterion checks.
fn isa_oracle_lemma(name: &str, prop: &str) -> String {
    isa_oracle_lemma_via("adsmt", name, prop)
}

/// Same, through a NAMED oracle — so a user assumption and a theory
/// decision are two distinct entries in `Thm_Deps.all_oracles` rather
/// than one indistinguishable count.
fn isa_oracle_lemma_via(oracle: &str, name: &str, prop: &str) -> String {
    // `\<^cprop>`, not `\<^cterm>`: an oracle's result must have type
    // `prop`. A statement like `q \<Longrightarrow> False` is already a
    // `prop` and passes either way, but a bare `bool` proposition — the
    // shape a user assumption takes — is rejected with "Oracle's result
    // must have type prop" unless it goes through `Trueprop`, which is
    // exactly what `\<^cprop>` inserts.
    format!(
        "lemma {name}: \"{prop}\"\n  \
         by (tactic \\<open>resolve_tac \\<^context> \
         [{oracle} \\<^cprop>\\<open>{prop}\\<close>] 1\\<close>)"
    )
}

/// The Isabelle **session** for the emitted theory.
///
/// The emitted `.thy` is Isabelle/HOL-specific — `Main`, `bool`, the
/// `\<Longrightarrow>` / `Trueprop` boundary, HOL tactics. Shipping the ROOT
/// alongside it pins that dependency in a file rather than leaving it
/// implicit, and it is what makes `isabelle build` runnable at all: the
/// acceptance criterion is stated in terms of that command.
pub fn emit_isabelle_root() -> String {
    "chapter AdsmtCert\n\n\
     session AdsmtCert = HOL +\n  \
     description \"adsmt certificate, emitted\"\n  \
     options [timeout = 300]\n  \
     theories\n    AdsmtCert\n"
        .to_owned()
}

/// Constants the emitter knows how to render. Anything else is an
/// UNMAPPED symbol: adsmt's name is passed through verbatim, which is
/// how `> x 5` once reached Isabelle as prefix application and failed to
/// parse. Callers can ask for the list to surface the gap instead of
/// discovering it downstream.
pub fn unmapped_constants(cert: &Certificate) -> Vec<String> {
    const KNOWN: &[&str] = &[
        "true", "false", "not", "and", "or", "implies", "=>", "iff", "=",
        "<", "<=", ">", ">=", "+", "-", "*",
    ];
    let mut out: Vec<String> = Vec::new();
    fn walk(t: &Term, known: &[&str], out: &mut Vec<String>) {
        match t.kind() {
            TermInner::Const(c) => {
                let n = c.name.as_str();
                // Numeric literals render as themselves in every target.
                let numeric = !n.is_empty()
                    && n.chars().all(|ch| ch.is_ascii_digit() || ch == '-');
                if !numeric && !known.contains(&n) && !out.iter().any(|x| x == n) {
                    out.push(n.to_owned());
                }
            }
            TermInner::App(f, x) => {
                walk(&f, known, out);
                walk(&x, known, out);
            }
            TermInner::Lam(_, b) => walk(&b, known, out),
            _ => {}
        }
    }
    for step in &cert.steps {
        for h in &step.result.hyps {
            walk(h, KNOWN, &mut out);
        }
        walk(&step.result.concl, KNOWN, &mut out);
    }
    out
}
